ajax_solr_search: null
solr-server-url: 'https://dsu-fedora.utsc.utoronto.ca:8983/solr/multisite'
solr-proxy-enabled: 1
search-results-path: /federated-search
solr-searchable-fields:
  - tm_X3b_en_fulltext_title
  - tm_X3b_en_description
  - sm_genre
  - sm_geographic_subject
  - sm_subject
  - sm_linked_agent
  - ss_resource_type
sub-query-field-name: null
sub-query-value: null
solr-facets-fields:
  -
    fname: ss_islandora_site_name
    label: Site
  -
    fname: sm_genre
    label: Genre
  -
    fname: sm_geographic_subject
    label: 'Geographic Subject'
  -
    fname: sm_linked_agent
    label: 'Linked Agent'
  -
    fname: ss_resource_type
    label: 'Resource Type'
solr-condition-fields:
  -
    fname: ss_type
    op: '='
    label: islandora_object
  -
    fname: its_nid
    op: '!null'
    label: ''
  -
    fname: site
    op: '!='
    label: 'https://griot.digital.utsc.utoronto.ca/'
  -
    fname: ss_islandora_model
    op: '!='
    label: Page
  -
    fname: site
    op: '!='
    label: 'https://doris2.digital.utsc.utoronto.ca/'
  -
    fname: site
    op: '!='
    label: 'http://tamil2.digital.utsc.utoronto.ca/'
  -
    fname: site
    op: '!='
    label: 'http://tamil2.digital.utsc.utoronto.ca/ta'
  -
    fname: site
    op: '!='
    label: 'https://tamil2.digital.utsc.utoronto.ca/ta'
output-template: "<div class=\"node\">\r\n      <div class=\"thumb\"><img src=\"{{ ss_islandora_object_thumbnail }}\" alt=\"{{ sm_media_file_alt_text }}\"/></div>\r\n      <div class=\"others\">\r\n        <p><h2><a href=\"{{ site }}/node/{{ its_nid }}\" target=\"_blank\">{{ ss_title }}</a></h2></p>\r\n        <p><strong>Description</strong>: {{ tm_X3b_en_field_description }}</p>\r\n      </div>\r\n    </div>\r\n    <hr />\r\n   "
solr-results-html:
  -
    fname: ss_islandora_object_thumbnail
    label: ''
  -
    fname: ss_title
    label: ''
  -
    fname: tm_X3b_en_field_description
    label: ''
  -
    fname: site
    label: ''
  -
    fname: its_nid
    label: ''
  -
    fname: ss_url
    label: URL
  -
    fname: sm_media_file_alt_text
    label: ''
rewrite-search-results-output: 1
search-instruction: "<strong>Search tips:</strong>\r\n<ul>\r\n<li>Using <code>~</code> for <a href=\"https://solr.apache.org/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-FuzzySearches\" target=\"_blank\">fuzzy search</a></li>\r\n<li>Using <code>*</code> for <a href=\"https://solr.apache.org/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-WildcardSearches\" target=\"_blank\">wildcard search</a></li>\r\n<li>Using <code>\"\"</code> for exact match search</li>\r\n</ul>"
items-per-page: '15'
