ajax_solr_search: null
solr-server-url: 'https://dsu-fedora.utsc.utoronto.ca:8983/solr/multisite'
solr-proxy-enabled: 0
search-results-path: /federated-search
solr-searchable-fields:
  - ss_title
  - tm_X3b_en_description
  - sm_genre
  - sm_geographic_subject
  - sm_subject
  - sm_linked_agent
  - ss_resource_type
sub-query-field-name: null
sub-query-value: null
solr-facets-fields:
  -
    fname: site
    label: Site
  -
    fname: sm_genre
    label: Genre
  -
    fname: sm_geographic_subject
    label: 'Geographic Subject'
  -
    fname: sm_linked_agent
    label: 'Linked Agent'
  -
    fname: ss_resource_type
    label: 'Resource Type'
solr-condition-fields:
  -
    fname: ss_type
    op: '='
    label: islandora_object
  -
    fname: its_nid
    op: '!null'
    label: ''
  -
    fname: site
    op: '!='
    label: 'https://griot.digital.utsc.utoronto.ca/'
  -
    fname: ss_islandora_model
    op: '!='
    label: Page
output-template: |-
  <div class="node">
        <div class="thumb"><img src="{{ sm_media_thumbnail_url }}" alt="thumbnail"/></div>
        <div class="others">
          <p><h2><a href="{{ site }}/node/{{ its_nid }}" target="_blank">{{ ss_title }}</a></h2></p>
          <p><strong>Description</strong>: {{ tm_X3b_en_field_description }}</p>
          <p><strong>{{ URL }}: </strong>{{ ss_url }}</p>
        </div>
      </div>
      <hr />
     
solr-results-html:
  -
    fname: sm_media_thumbnail_url
    label: ''
  -
    fname: ss_title
    label: ''
  -
    fname: tm_X3b_en_field_description
    label: ''
  -
    fname: site
    label: ''
  -
    fname: its_nid
    label: ''
  -
    fname: ss_url
    label: URL
rewrite-search-results-output: 0
